import ClientProvider from "@/ClientProvider";
import type { Metadata } from "next";
import { ThemeProvider } from "next-themes";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <main className="min-h-screen items-center justify-center">
            <ThemeProvider>
                <ClientProvider>
                    {children}
                </ClientProvider>
            </ThemeProvider>
        </main>
    );
}
